In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("eu-27_pm2.5_transport_emissions_as_reported_to_the_convention_on_long-range_transboundary_air_pollution_(lrtap_convention) (1).csv", skiprows=11)

In [7]:
df

,AT Cars - PM2.5 emissions (Gg),AT Domestic aviation LTO - PM2.5 emissions (Gg),AT Domestic aviation cruise - PM2.5 emissions (Gg),AT Domestic navigation - PM2.5 emissions (Gg),AT Heavy duty vehicles and buses - PM2.5 emissions (Gg),AT International aviation LTO - PM2.5 emissions (Gg),AT International aviation cruise - PM2.5 emissions (Gg),AT International inland waterways - PM2.5 emissions (Gg),AT Other mobile - PM2.5 emissions (Gg),AT Powered two-wheelers - PM2.5 emissions (Gg),...,y_454,y_455,y_456,y_457,y_458,y_459,y_460,y_461,y_462,y_463
0,1.605570,0.003545,0.007314,0.017606,2.459570,0.039964,0.262452,0.039166,0.021239,0.126757,...,0.002416,0.014181,0.007993,0.074958,0.502075,0.001538,0.028206,0.079857,0.10182,0.531809
1,1.705278,0.003865,0.008066,0.018584,2.513938,0.044073,0.289433,0.040980,0.020606,0.123299,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.804986,0.004185,0.008818,0.019563,2.568306,0.048181,0.316414,0.042794,0.019974,0.119842,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.904694,0.004505,0.009570,0.020542,2.622674,0.052290,0.343394,0.044608,0.019341,0.116384,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.004402,0.004826,0.010322,0.021521,2.677042,0.056398,0.370375,0.046422,0.018709,0.112927,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2.104110,0.005146,0.011074,0.022500,2.731410,0.060506,0.397356,0.048236,0.018076,0.109469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.211198,0.005499,0.011713,0.023558,2.654074,0.062854,0.419916,0.049637,0.018113,0.109188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.318286,0.005852,0.012353,0.024616,2.576738,0.065202,0.442476,0.051038,0.018150,0.108906,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2.425374,0.006205,0.012993,0.025674,2.499402,0.067549,0.465036,0.052439,0.018186,0.108625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.532462,0.006558,0.013632,0.026732,2.422066,0.069897,0.487596,0.053841,0.018223,0.108343,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2.639550,0.006911,0.014272,0.027790,2.344730,0.072245,0.510156,0.055242,0.018260,0.108062,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.786240,0.005696,0.013177,0.028148,2.319560,0.068584,0.498600,0.058011,0.017976,0.106783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3.080090,0.005992,0.013137,0.028568,2.250110,0.080186,0.449067,0.064601,0.017668,0.105731,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3.265570,0.005895,0.013163,0.029325,2.213460,0.083555,0.415515,0.050996,0.017354,0.105031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3.285480,0.006272,0.013577,0.034704,2.096740,0.099674,0.492810,0.060200,0.017060,0.103287,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,3.263530,0.006040,0.014287,0.035569,1.990870,0.092859,0.580309,0.057497,0.017053,0.104566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3.298580,0.007131,0.014834,0.036499,1.664320,0.091992,0.611763,0.048935,0.017051,0.105935,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3.174490,0.007273,0.015367,0.035043,1.430770,0.099478,0.647869,0.050029,0.017061,0.107602,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2.690090,0.008048,0.013511,0.033889,1.174510,0.101096,0.648371,0.044207,0.017078,0.109253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2.390720,0.007473,0.012646,0.034283,0.988454,0.092494,0.557857,0.036040,0.016436,0.109791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2.270500,0.007093,0.011993,0.034866,0.928336,0.094838,0.609146,0.040895,0.015809,0.108887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2.013380,0.006401,0.010714,0.037074,0.753721,0.107850,0.636970,0.034451,0.015030,0.107753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1.757410,0.006179,0.010218,0.032986,0.671282,0.103672,0.608248,0.034334,0.014408,0.106788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1.542880,0.006174,0.010138,0.034586,0.677274,0.100872,0.577658,0.035880,0.013798,0.104597,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1.384830,0.005629,0.009277,0.038132,0.561286,0.101989,0.577443,0.032507,0.013224,0.102320,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1.278200,0.005516,0.009137,0.038407,0.474161,0.107719,0.623354,0.026126,0.012588,0.100270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1.154780,0.005556,0.007742,0.039404,0.392112,0.110152,0.688765,0.027853,0.012051,0.098765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1.014420,0.005079,0.007314,0.041096,0.326478,0.106681,0.665146,0.027823,0.011425,0.097934,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.847723,0.005868,0.007840,0.041975,0.272521,0.115986,0.753438,0.019892,0.010937,0.083553,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.693637,0.005981,0.007864,0.046464,0.233840,0.131298,0.869511,0.022477,0.010367,0.099457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0.491581,0.002922,0.003394,0.010195,0.177608,0.050959,0.308573,0.020806,0.009812,0.091523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.436015,0.003047,0.003318,0.017275,0.151659,0.059709,0.363112,0.018701,0.009568,0.085620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,0.391694,0.003824,0.004766,0.037160,0.107906,0.095724,0.580248,0.015237,0.009312,0.079161,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
eu_cols = [col for col in df.columns if col.startswith("EU")]
print(eu_cols)

['EU-27 Cars - PM2.5 emissions (Gg)', 'EU-27 Domestic aviation LTO - PM2.5 emissions (Gg)', 'EU-27 Domestic aviation cruise - PM2.5 emissions (Gg)', 'EU-27 Domestic navigation - PM2.5 emissions (Gg)', 'EU-27 Heavy duty vehicles and buses - PM2.5 emissions (Gg)', 'EU-27 International aviation LTO - PM2.5 emissions (Gg)', 'EU-27 International aviation cruise - PM2.5 emissions (Gg)', 'EU-27 International inland waterways - PM2.5 emissions (Gg)', 'EU-27 International navigation - PM2.5 emissions (Gg)', 'EU-27 Other mobile - PM2.5 emissions (Gg)', 'EU-27 Powered two-wheelers - PM2.5 emissions (Gg)', 'EU-27 Rail - PM2.5 emissions (Gg)', 'EU-27 Road non-exhaust - PM2.5 emissions (Gg)', 'EU-27 Vans - PM2.5 emissions (Gg)']

In [14]:
df_eu = df[['EU-27 Cars - PM2.5 emissions (Gg)', 'EU-27 Domestic aviation LTO - PM2.5 emissions (Gg)', 'EU-27 Domestic aviation cruise - PM2.5 emissions (Gg)', 'EU-27 Domestic navigation - PM2.5 emissions (Gg)', 'EU-27 Heavy duty vehicles and buses - PM2.5 emissions (Gg)', 'EU-27 International aviation LTO - PM2.5 emissions (Gg)', 'EU-27 International aviation cruise - PM2.5 emissions (Gg)', 'EU-27 International inland waterways - PM2.5 emissions (Gg)', 'EU-27 International navigation - PM2.5 emissions (Gg)', 'EU-27 Other mobile - PM2.5 emissions (Gg)', 'EU-27 Powered two-wheelers - PM2.5 emissions (Gg)', 'EU-27 Rail - PM2.5 emissions (Gg)', 'EU-27 Road non-exhaust - PM2.5 emissions (Gg)', 'EU-27 Vans - PM2.5 emissions (Gg)']]

In [19]:
# since Temporal coverage
#1990-2023
# https://www.eea.europa.eu/en/analysis/publications/sustainability-of-europes-mobility-systems-2025/air-pollution/eu-27-pm2-5-transport-emissions-as-reported-to-the-convention-on-long-range-transboundary-air-pollution-lrtap-convention?activeTab=8a280073-bf94-4717-b3e2-1374b57ca99d

In [18]:
df_eu.index = range(1990, 2024)
df_eu

,EU-27 Cars - PM2.5 emissions (Gg),EU-27 Domestic aviation LTO - PM2.5 emissions (Gg),EU-27 Domestic aviation cruise - PM2.5 emissions (Gg),EU-27 Domestic navigation - PM2.5 emissions (Gg),EU-27 Heavy duty vehicles and buses - PM2.5 emissions (Gg),EU-27 International aviation LTO - PM2.5 emissions (Gg),EU-27 International aviation cruise - PM2.5 emissions (Gg),EU-27 International inland waterways - PM2.5 emissions (Gg),EU-27 International navigation - PM2.5 emissions (Gg),EU-27 Other mobile - PM2.5 emissions (Gg),EU-27 Powered two-wheelers - PM2.5 emissions (Gg),EU-27 Rail - PM2.5 emissions (Gg),EU-27 Road non-exhaust - PM2.5 emissions (Gg),EU-27 Vans - PM2.5 emissions (Gg)
1990,99.227749,0.380428,0.455143,23.104572,113.509292,0.729735,3.481724,1.313753,114.654259,4.199566,9.226996,14.055206,36.343067,65.550660
1991,99.648846,0.376788,0.436975,24.185699,111.373905,0.741174,3.450991,1.444055,110.473292,4.388341,9.150990,13.182841,37.042390,68.067313
1992,98.286400,0.387932,0.429237,22.729821,110.653107,0.754949,3.565585,1.398062,112.874413,4.252607,9.653464,12.757459,38.467477,67.975260
1993,98.061253,0.375938,0.429465,20.927754,105.826450,0.731269,3.666836,1.296994,117.982885,4.364251,10.222605,12.579194,39.154363,70.840310
1994,93.710665,0.383756,0.454583,20.428551,101.735717,0.750554,3.761306,1.388434,118.773706,4.240950,10.102635,11.980474,40.208284,70.095623
1995,93.508713,0.412430,0.458753,20.169008,98.630749,0.766321,3.905114,1.395734,121.271013,4.308214,9.995071,11.810211,41.312242,68.765194
1996,93.165692,0.423688,0.474851,21.009026,94.615342,0.768664,4.040571,1.335890,116.532467,3.519322,10.035129,11.137655,42.717915,67.722439
1997,88.373937,0.439181,0.510954,21.652764,90.913347,0.786659,4.183452,1.196392,121.705277,3.685437,10.183806,11.097075,44.120195,64.293971
1998,89.161786,0.460894,0.511592,22.581215,87.200002,0.852605,4.291062,1.156144,125.303982,3.540276,10.494173,10.869700,45.698266,63.329667
1999,87.608618,0.489413,0.533310,20.423303,83.750772,0.899963,4.508657,0.991620,126.447689,3.318709,10.399265,10.358139,47.272915,61.375383
2000,84.718116,0.523786,0.534866,19.362137,77.947426,1.161610,4.648567,0.988299,133.020209,2.915544,9.084115,10.418597,47.521811,57.209260
2001,82.656629,0.532999,0.501716,19.354535,73.695021,1.118243,4.578297,1.035305,133.217804,2.312526,8.640687,9.710368,49.379140,57.017817
2002,81.130861,0.534170,0.495606,18.861554,69.292700,1.113763,4.438569,0.979019,134.204425,2.222807,8.271441,9.297207,50.739551,53.300695
2003,80.371877,0.513395,0.488227,19.189342,65.229210,1.156616,4.484747,0.890510,147.741112,2.682459,7.716397,9.214234,52.285475,51.800743
2004,79.655201,0.567188,0.491509,18.332379,63.880034,1.228973,4.745582,0.911205,157.119722,3.388843,7.109189,9.132042,53.747651,50.112021
2005,75.592245,0.582866,0.490054,17.922988,60.947653,1.268684,5.023100,0.936241,156.504557,3.716034,6.097637,8.650932,54.835065,45.825458
2006,73.469926,0.581279,0.499954,17.465123,59.669368,1.337017,5.194162,0.962800,140.013084,3.251794,5.423505,8.674859,56.475798,42.785417
2007,71.977175,0.587349,0.514382,16.594374,53.996116,1.417260,5.391424,0.963818,143.635932,3.167392,4.752214,8.668517,58.261003,40.485671
2008,69.417776,0.533091,0.480361,15.572536,46.065436,1.407993,5.508478,1.016768,137.847520,2.954806,4.601446,8.653809,57.633127,36.335608
2009,66.509635,0.597550,0.449775,15.841189,39.004617,1.282589,4.935187,0.806674,126.619401,3.126154,4.288032,7.716555,56.956711,31.967146
2010,64.010992,0.564022,0.449820,15.737832,34.974923,1.328326,5.012215,0.821662,115.074939,2.678226,3.812376,7.727256,56.704553,30.136230
2011,56.929578,0.526935,0.446246,14.627141,31.177573,1.386700,5.074503,0.748257,114.033747,2.430901,3.583305,7.654904,57.328347,27.610655
2012,52.130883,0.528718,0.404069,13.437798,27.899750,1.442039,5.015611,0.699464,111.381288,2.206426,3.427892,7.553880,55.224533,24.707635
2013,48.885318,0.473461,0.360612,12.560327,24.484255,1.376044,4.988589,0.693904,102.287290,2.467914,3.271211,7.163009,54.995166,21.454982
2014,44.618194,0.472334,0.356401,12.489830,21.869336,1.455913,5.038777,0.701641,98.561818,2.365683,3.057086,7.176333,56.355578,18.898153
2015,42.836217,0.496000,0.375286,11.707507,18.948858,1.556289,5.325513,0.685855,82.842407,2.244789,3.021457,7.227567,57.490812,17.821086
2016,40.478060,0.586853,0.387372,12.594905,17.370206,1.675070,5.631730,0.653210,91.119269,2.144354,2.756274,7.066840,58.613989,15.791164
2017,38.117187,0.638388,0.399698,13.189329,16.040243,1.827015,6.005583,0.654610,91.573596,1.944001,2.620578,6.932864,59.745896,14.434306
2018,34.179051,0.649149,0.421599,14.074752,14.920188,1.937335,6.357749,0.619364,88.839741,1.927690,2.490590,6.912471,60.970169,13.129457
2019,31.408066,0.633330,0.413391,15.208289,13.295887,1.981829,6.540609,0.600493,86.617829,2.088973,2.453753,6.697911,61.266898,11.573134
2020,24.193108,0.345349,0.220553,14.547222,10.974070,0.755395,2.675996,0.588388,64.950210,2.192509,2.212301,6.054379,54.299257,9.235166
2021,23.986518,0.432980,0.276281,12.630233,10.034826,0.924792,3.380356,0.600701,67.134418,2.016869,2.119370,6.503807,58.499123,9.517099
2022,22.642414,0.448063,0.363311,14.471101,9.373901,1.299026,5.322015,0.551051,70.926071,2.094543,2.160411,6.670100,60.628362,8.631921
2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
bus_22 = df_eu.loc[2022,"EU-27 Heavy duty vehicles and buses - PM2.5 emissions (Gg)"]
bus_92 = df_eu.loc[1992,"EU-27 Heavy duty vehicles and buses - PM2.5 emissions (Gg)"]
(bus_22 - bus_92)/ bus_92

np.float64(-0.9152856960999232)

In [31]:
road_22 = df_eu.loc[2022,"EU-27 Road non-exhaust - PM2.5 emissions (Gg)"]
road_92 = df_eu.loc[1992,"EU-27 Road non-exhaust - PM2.5 emissions (Gg)"]
(road_22 - road_92)/ road_92

np.float64(0.5760940619594724)